<a href="https://colab.research.google.com/github/3dgarxx3/Mineria_Datos/blob/main/Libreta1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Primer parcial

### Introduccion

#### Conceptos

Es el proceso de extraer informacion util a partir de una acumulacion de datos.

#### Ciencia de datos

Es un término que incluye muchas tecnologías de la información, tales como estadística, matemática y técnicas informáticas sofisticadas, aplicadas a los datos.

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de mostrar ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

IPython Magic Commands

In [2]:
# Sirve para evaluar el desempeño de una expreson en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

70.3 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
# Con doble porcentaje podemos evaluar el desempeño
# en cuanto tiempo de mas de una linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

78.7 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands


In [5]:
!ls

sample_data


In [7]:
!pwd

/content


In [8]:
!echo "printing from the shell"

printing from the shell


In [9]:
contents = !ls

In [10]:
print(contents)
['myproject.txt']

['sample_data']


['myproject.txt']

In [11]:
directory = !pwd

In [17]:
print(directory)

['/content']


In [13]:
type(directory)

IPython.utils.text.SList

In [14]:
type(directory)

IPython.utils.text.SList

In [15]:
message = "hello from Python"

In [16]:
!echo {message}

hello from Python


In [18]:
%cd /content/

/content


In [19]:
%ls

sample_data/


In [21]:
%cd sample_data/

/content/sample_data


Understanding Data Types in Python

In [22]:
# importa numpy y renombralo como np
import numpy as np

In [23]:
# Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [25]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [26]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [27]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [29]:
# Cuando el argumento de np.array es una iteraccion anidada
#genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])