<a href="https://colab.research.google.com/github/3dgarxx3/Mineria_Datos/blob/main/Libreta1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Primer parcial

### Introduccion

#### Conceptos

Es el proceso de extraer informacion util a partir de una acumulacion de datos.

#### Ciencia de datos

Es un término que incluye muchas tecnologías de la información, tales como estadística, matemática y técnicas informáticas sofisticadas, aplicadas a los datos.

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de mostrar ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

IPython Magic Commands

In [ ]:
# Sirve para evaluar el desempeño de una expreson en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

70.3 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Con doble porcentaje podemos evaluar el desempeño
# en cuanto tiempo de mas de una linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

78.7 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands


In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)
['myproject.txt']

['sample_data']


['myproject.txt']

In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/

/content


In [ ]:
%ls

sample_data/


In [ ]:
%cd sample_data/

/content/sample_data


Understanding Data Types in Python

In [ ]:
# importa numpy y renombralo como np
import numpy as np

In [ ]:
# Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
# Cuando el argumento de np.array es una iteraccion anidada
#genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [1]:
import numpy as np

In [2]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.60370971, 0.09233299, 0.48813468],
       [0.96604432, 0.33726125, 0.24186617],
       [0.97256237, 0.60233565, 0.99684111]])

In [9]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.30336364, -0.46743784, -0.69912043],
       [ 0.56631395,  0.29079024, -0.6196249 ],
       [-0.98140967,  0.70075   , -1.1669079 ]])

In [10]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 5, 1],
       [8, 6, 1],
       [7, 9, 6]])

In [11]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

###The Basics of NumPy Arrays

####NumPy Array Attributes

In [13]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [14]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [15]:
print("dtype:", x3.dtype)

dtype: int64


In [16]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


####Array Indexing: Accessing Single Elements

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
#Me trae la posicion de los arreglos
x1[0]

np.int64(5)

In [19]:
x1[4]

np.int64(7)

In [20]:
x1[-2]

np.int64(7)

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
#Direcciona las posiciones
x2[0, 0]

np.int64(3)

In [25]:
x2[-1, -1] = 2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

###Promedio (Average) y Promedio Ponderado

> Agregar bloque entrecomillado



In [26]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

### Mediana

In [27]:
mediana = np.median(data)

### Varianza y Desviación Estándar

In [28]:
varianza = np.var(data)
desviacion = np.std(data)

###Generación de Datos Aleatorios

In [29]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


### Correlación

In [30]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
